spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    disable-html-escaping: false
  application:
    name: sbp
  datasource:
    #    Note: URL for the mariadb is passed as an argument.
    #    Add the following IntelliJ Environment Variables in:
    #    Edit Configurations >> Environment >> Environment Variables
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:mariadb://${DB_IP_ADDR}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  batch:
    jdbc:
      initialize-schema: NEVER

---
hibernate:
  create_empty_composites:
    enabled: false

---
dir:
  csv-files:
    cwd: file://Users/sean/env/pty/proj/microservices/pay-cons/src/main/resources/samples/*.csv
    in: /env/dev/files/csv/in
    procd: /env/dev/files/csv/procd
    err: /env/dev/files/csv/error

---
spring:
  cloud:
    dataflow:
      applicationProperties:
        stream:
          management:
            endpoint:
              health:
                show-components: always
                show-details: always
            endpoints:
              jmx:
                exposure:
                  include: '*'
              web:
                exposure:
                  include: '*'
            metrics:
              export:
                prometheus:
                  enabled: true
                  rsocket:
                    enabled: true
                    host: prometheus-rsocket-proxy
                    port: 7001
