apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sbp
  labels:
    app: sbp
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
